### ISSUE TITLE
Error: Cannot find module './lib/RiscoTCPPanel'

### ISSUE THREAD

**Issue by andyblac** [gawindx/homebridge-risco-local-platform#4]
just updated to version `0.1.3` and now get this.
```
[14/10/2021, 18:57:56] Registering platform 'homebridge-harmony.HarmonyHubWebSocket'
[14/10/2021, 18:57:56] ---
[14/10/2021, 18:57:56] ====================
[14/10/2021, 18:57:56] ERROR LOADING PLUGIN homebridge-risco-local-platform:
[14/10/2021, 18:57:56] Error: Cannot find module './lib/RiscoTCPPanel'
Require stack:
- /usr/local/lib/node_modules/homebridge-risco-local-platform/node_modules/risco-lan-bridge/index.js
- /usr/local/lib/node_modules/homebridge-risco-local-platform/app.js
- /usr/local/lib/node_modules/homebridge/lib/plugin.js
- /usr/local/lib/node_modules/homebridge/lib/pluginManager.js
- /usr/local/lib/node_modules/homebridge/lib/server.js
- /usr/local/lib/node_modules/homebridge/lib/cli.js
- /usr/local/lib/node_modules/homebridge/bin/homebridge
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:880:15)
    at Function.Module._load (internal/modules/cjs/loader.js:725:27)
    at Module.require (internal/modules/cjs/loader.js:952:19)
    at require (internal/modules/cjs/helpers.js:88:18)
    at Object.<anonymous> (/usr/local/lib/node_modules/homebridge-risco-local-platform/node_modules/risco-lan-bridge/index.js:28:18)
    at Module._compile (internal/modules/cjs/loader.js:1063:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1092:10)
    at Module.load (internal/modules/cjs/loader.js:928:32)
    at Function.Module._load (internal/modules/cjs/loader.js:769:14)
    at Module.require (internal/modules/cjs/loader.js:952:19)
[14/10/2021, 18:57:56] ====================
```

**Comment by andyblac** [comment]
file and modules have been renamed see here https://github.com/TJForc/risco-lan-bridge/commit/78ac97fea8cee0b7b760f0377e58d282254539e2#diff-76b5a357391276b282a516f54f48ef3c207f46d8192dc58c208d5183d38415f8

https://github.com/TJForc/risco-lan-bridge/commit/9e1cf91107b94e51741d8e24cb103e0988f8b945#diff-76b5a357391276b282a516f54f48ef3c207f46d8192dc58c208d5183d38415f8

https://github.com/TJForc/risco-lan-bridge/commit/1d2f2882a9560acd7550c9b3ad157538f78b8f65#diff-76b5a357391276b282a516f54f48ef3c207f46d8192dc58c208d5183d38415f8

https://github.com/TJForc/risco-lan-bridge/commit/484854c03e8699ecf20ee9259da35ef028a1b580#diff-76b5a357391276b282a516f54f48ef3c207f46d8192dc58c208d5183d38415f8

**Comment by TJForc** [comment]
Sure enough, the error is in my code.
My test environment did not allow me to see that I had forgotten to rename this export.
it is corrected on my side.
To solve your problem, all you have to do is install a previous version of 'homebridge-risco-local-platform' and then update the plugin again via the Homebridge web interface.

**Comment by gawindx** [comment]
I had the right too.
it works again on my side.

**Comment by andyblac** [comment]
yup all working now thx
